#!/usr/bin/env python3
import argparse
import json
import sys
from pathlib import Path

NETSCAPE_HEADER = """# Netscape HTTP Cookie File
# This file was generated by yt_cookies_json_to_cookies_txt.py
#
# Format:
# domain\tinclude_subdomains\tpath\tsecure\texpires\tname\tvalue
"""


def bool_flag(value: bool) -> str:
    return "TRUE" if value else "FALSE"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Convert yt-dlp JSON cookies (yt-cookies.json) to Netscape cookies.txt",
    )
    parser.add_argument(
        "input",
        nargs="?",
        default="yt-cookies.json",
        help="Input JSON cookie file (default: yt-cookies.json)",
    )
    parser.add_argument(
        "output",
        nargs="?",
        default="cookies.txt",
        help="Output Netscape cookies.txt (default: cookies.txt)",
    )
    args = parser.parse_args()

    input_path = Path(args.input)
    output_path = Path(args.output)

    try:
        cookies = json.loads(input_path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        print(f"ERROR: input file not found: {input_path}", file=sys.stderr)
        return 2
    except json.JSONDecodeError as e:
        print(f"ERROR: invalid JSON in {input_path}: {e}", file=sys.stderr)
        return 2

    if not isinstance(cookies, list):
        print("ERROR: expected a JSON array of cookie objects", file=sys.stderr)
        return 2

    lines = [NETSCAPE_HEADER.rstrip("\n")]

    for idx, cookie in enumerate(cookies):
        if not isinstance(cookie, dict):
            continue

        name = str(cookie.get("name", "")).strip()
        value = str(cookie.get("value", "")).strip()
        domain = str(cookie.get("domain", "")).strip()
        path = str(cookie.get("path", "/")).strip() or "/"

        # yt-dlp accepts both JSON and Netscape formats; for Netscape, expires must be an int.
        expires_raw = cookie.get("expires", 0)
        try:
            expires = int(expires_raw) if expires_raw is not None else 0
        except (TypeError, ValueError):
            expires = 0

        secure = bool(cookie.get("secure", False))

        if not (name and domain):
            # Skip malformed entries
            continue

        include_subdomains = domain.startswith(".")

        # Netscape format uses TRUE/FALSE strings
        line = "\t".join(
            [
                domain,
                bool_flag(include_subdomains),
                path,
                bool_flag(secure),
                str(expires),
                name,
                value,
            ]
        )
        lines.append(line)

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {output_path} ({max(0, len(lines) - 1)} cookies)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
